version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - apt-get update && apt-get install -y unzip
  build:
    commands:
      - echo "Zipping application..."
      - zip -r app.zip app/ 
artifacts:
  files:
    - app.zip
